---
- hosts: centos
  user: root
  tasks:
    - name: Include a play after another play
      include: centos_repos.yml 
    - lineinfile:
        path: /etc/sudoers
        state: present
        regexp: '^%sudo'
        line: '%sudo ALL=(ALL) NOPASSWD: ALL'
        validate: 'visudo -cf %s'
    - name: remove the Apache package
      yum:
        name: httpd
        state: present
    - name: Install multiple packages
      yum:
        name:
          - git
          - sshpass
          - openssl-devel
          - docker-ce-19.03.4
          - docker-ce-cli-19.03.4
          #- kubernetes
          - kubernetes-cni
          - kubeadm
          - kubectl
          - fish
          - tmux
          - webmin
          - vim
        state: latest
    - name: Install yum utils
      yum:
        name: yum-utils
        state: latest

    - name: Install device-mapper-persistent-data
      yum:
        name: device-mapper-persistent-data
        state: latest

    - name: Install lvm2
      yum:
        name: lvm2
        state: latest


    - name: Install Docker
      package:
        name: docker-ce
        state: latest
      become: yes

    - name: Start Docker service
      service:
        name: docker
        state: started
        enabled: yes
      become: yes
  