---
#
# Ansible playbook: Webmin for Ubuntu v201501302302
# Louis T. Getterman IV (@LTGIV)
# www.GotGetLLC.com / www.opensour.cc
#
# Example Usage:
# [user@host ~$] ansible-playbook /etc/ansible/playbooks/webmin.yml --extra-vars 'target=nameFromHostsFile'
#
- hosts: pi
  sudo: yes
  user: pi
  tasks:
     - name: Upgrade all packages to the latest version
       apt:
         name: "*"
         state: latest
     - name: Add Webmin repositories
       apt_repository: >
        repo='{{ item }}'
        state=present
       with_items:
         - 'deb http://download.webmin.com/download/repository sarge contrib'
         #- 'deb https://download.webmin.com/download/repository sarge contrib'
         #- 'deb http://webmin.mirror.somersettechsolutions.co.uk/repository sarge contrib'

     - name: Add Webmin key
       apt_key: >
        url='http://www.webmin.com/jcameron-key.asc'
        state=present
     - name: Install Webmin and prerequisites
       apt: >
        update_cache=yes
        pkg={{ item }}
        state=present
       with_items:
         - perl
         - libnet-ssleay-perl
         - openssl
         - libauthen-pam-perl
         - libpam-runtime
         - libio-pty-perl
         - apt-show-versions
         - python
         - webmin
         - raspberrypi-kernel-headers